### ISSUE TITLE
moving JER to class function

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#221]
Since JER is just a function of eta in 7 bins, I think it might be best to just move this function
(https://github.com/vallot/CATTools/blob/cat75x/CatProducer/plugins/CATJetProducer.cc#L187)
to Jet.h

I think the same can be done for SF's and pileup weights. 
This way we dont have to remake catTuples when these weights change.

**Comment by jhgoh** [comment]
How about AnalysisHelper?

**Comment by jshlee** [comment]
for pileup yes
then i think AnalysisHelper should be moved to CatProducer or CommonTools
but since SF and JER etc depend on eta or pt and analysis object wise, it is easier to use.
plus I dont mind it being hard coded into particle objects

**Comment by jhgoh** [comment]
JER have to be propagated to MET, so the same code have to be also in MET.h
It's hard to imagine MET to keep all jet pt variations from JER so user have to copy usual MET variation routine - this is not preferred way.
So, something like
`AnalysisHelper::applyJER(jets, met, newJets, newMET);`
seems to be better for me but I cannot find strong advantage with this. 
Simply we can detach JER EDProducer from central production workflow and move into CatAnalyzer.

**Comment by jshlee** [comment]
if both jets and mets need to have JER applied, I agree that is the best way.
but for cases when only jets need to be updated, i think its nicer to have it in the jet object
and for met we can have 
newMET = AnalysisHelper::METapplyJER(jets, met);
without JER propagated to MET.h

**Comment by jhgoh** [comment]
We had some discussion on this issue this afternoon.
There can be many possibilities. Among them, adding JER in the dataformat seem to be best way because:
- Simplest user interface
- Reduces file size. No need to add additional field for JER variations
  As far as I understand, all CATTools related analyses reads catTuples using the full framework (or at least fwlite), no direct access to cat::Jet from plane root session. 

MET variation is quite tricky, but if we can assume all users can run EDProducer before having their ntuples/histograms, analyzers can be guided to produce MET variations on the fly.

**Comment by jhgoh** [comment]
Implemented JER in dataformat.

**Comment by jshlee** [comment]
done

**Comment by jhgoh** [comment]
Closing this issue.
