### ISSUE TITLE
isolation30 of lepton

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#87]
https://github.com/vallot/CATTools/blob/cat72x/CatProducer/plugins/CATMuonProducer.cc#L109
https://github.com/vallot/CATTools/blob/cat72x/CatProducer/plugins/CATElectronProducer.cc#L126

The code has to make chIso03, nhIso03, phIso03, puIso03.
However, the all-vaules for muon and electron are "-1" in catTuple(my test sample).
Please, check the part. I can't find the solution.

for more information,
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/PatCandidates/interface/Lepton.h#L82
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/RecoCandidate/interface/IsoDeposit.h
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/RecoCandidate/interface/IsoDepositDirection.h

**Comment by monttj** [comment]
You need a little tweak in PAT sequence.

https://github.com/vallot/CATTools/blob/72X_v1/CatProducer/python/Tools/tools.py#L49

It can be done in upstream. 

Since current workflow seems to follow miniAOD not the standard PAT sequence alone,
you need to touch the PAT sequence here.
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py

Can you try to do this?

Taejeong

**Comment by jshlee** [comment]
my newest pr (https://github.com/vallot/CATTools/pull/88) has iso03 in for both electrons and muons when run on AODs

**Comment by jshlee** [comment]
i'll close this once the pr is merged unless anyone else has any comments.

**Comment by YoungKwonJo** [comment]
I agree to close this issue.
